# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/USB DISK/Licks Python OK/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(368, 526)
        MainWindow.setMaximumSize(QtCore.QSize(442, 670))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}\n"
"\n"
"QBoxLayout {\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cont_Titulo = QtWidgets.QWidget(self.centralwidget)
        self.cont_Titulo.setMinimumSize(QtCore.QSize(0, 32))
        self.cont_Titulo.setObjectName("cont_Titulo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cont_Titulo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_titulo = QtWidgets.QPushButton(self.cont_Titulo)
        self.btn_titulo.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_titulo.setFont(font)
        self.btn_titulo.setStyleSheet("border: 1px solid black;\n"
"border-radius: 4px;\n"
"background: solid white;")
        self.btn_titulo.setObjectName("btn_titulo")
        self.verticalLayout_2.addWidget(self.btn_titulo)
        self.verticalLayout.addWidget(self.cont_Titulo)
        self.cont_Main = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cont_Main.sizePolicy().hasHeightForWidth())
        self.cont_Main.setSizePolicy(sizePolicy)
        self.cont_Main.setObjectName("cont_Main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cont_Main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.cont_Main)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 470))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vLayout = QtWidgets.QVBoxLayout()
        self.vLayout.setContentsMargins(0, 0, 0, 0)
        self.vLayout.setObjectName("vLayout")
        self.verticalLayout_4.addLayout(self.vLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.cont_Main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_titulo.setText(_translate("MainWindow", "Licks - Categorías:"))
