# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_password(object):
    def setupUi(self, Form_password):
        Form_password.setObjectName("Form_password")
        Form_password.resize(329, 126)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_password)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form_password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setGeometry(QtCore.QRect(9, 0, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.txt_password = QtWidgets.QLineEdit(self.widget)
        self.txt_password.setGeometry(QtCore.QRect(9, 30, 311, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txt_password.setFont(font)
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_password.setObjectName("txt_password")
        self.verticalLayout_2.addWidget(self.widget)
        self.btn_aceptar = QtWidgets.QPushButton(Form_password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_aceptar.sizePolicy().hasHeightForWidth())
        self.btn_aceptar.setSizePolicy(sizePolicy)
        self.btn_aceptar.setMinimumSize(QtCore.QSize(91, 41))
        self.btn_aceptar.setMaximumSize(QtCore.QSize(91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_aceptar.setFont(font)
        self.btn_aceptar.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.verticalLayout_2.addWidget(self.btn_aceptar, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(Form_password)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_mensajeEstado = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lbl_mensajeEstado.setFont(font)
        self.lbl_mensajeEstado.setStyleSheet("color: rgb(109, 109, 109);")
        self.lbl_mensajeEstado.setText("")
        self.lbl_mensajeEstado.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_mensajeEstado.setObjectName("lbl_mensajeEstado")
        self.verticalLayout.addWidget(self.lbl_mensajeEstado)
        self.verticalLayout_2.addWidget(self.widget_2)

        self.retranslateUi(Form_password)
        self.txt_password.returnPressed.connect(self.btn_aceptar.click)
        QtCore.QMetaObject.connectSlotsByName(Form_password)

    def retranslateUi(self, Form_password):
        _translate = QtCore.QCoreApplication.translate
        Form_password.setWindowTitle(_translate("Form_password", "Contraseña"))
        self.label_15.setText(_translate("Form_password", "Introducir contraseña:"))
        self.btn_aceptar.setText(_translate("Form_password", "Aceptar"))
