# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/USB DISK/Licks Python OK/ui_subfolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubFolderWindow(object):
    def setupUi(self, SubFolderWindow):
        SubFolderWindow.setObjectName("SubFolderWindow")
        SubFolderWindow.resize(600, 585)
        SubFolderWindow.setMaximumSize(QtCore.QSize(600, 9999))
        SubFolderWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}\n"
"\n"
"QBoxLayout {\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(SubFolderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cont_Main = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cont_Main.sizePolicy().hasHeightForWidth())
        self.cont_Main.setSizePolicy(sizePolicy)
        self.cont_Main.setObjectName("cont_Main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cont_Main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.cont_Main)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 582, 567))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid black;\n"
"    border-radius: 4px;\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vLayout = QtWidgets.QVBoxLayout()
        self.vLayout.setContentsMargins(0, 0, 0, 0)
        self.vLayout.setObjectName("vLayout")
        self.verticalLayout_4.addLayout(self.vLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.cont_Main)
        SubFolderWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SubFolderWindow)
        QtCore.QMetaObject.connectSlotsByName(SubFolderWindow)

    def retranslateUi(self, SubFolderWindow):
        _translate = QtCore.QCoreApplication.translate
        SubFolderWindow.setWindowTitle(_translate("SubFolderWindow", "MainWindow"))
