# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tablaFilasResultados.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowTablaResult(object):
    def setupUi(self, WindowTablaResult):
        WindowTablaResult.setObjectName("WindowTablaResult")
        WindowTablaResult.resize(1124, 693)
        self.centralwidget = QtWidgets.QWidget(WindowTablaResult)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_filasResultados = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_filasResultados.setStyleSheet("QTableView::item:selected {\n"
"    color: black;\n"
"    background: rgb(235, 245, 255);\n"
"    font-weight:900;\n"
"    border: 1px solid grey;\n"
"}\n"
"QTableCornerButton::section {background-color: rgb(235, 245, 255) }\n"
"QHeaderView::section {\n"
"    background-color: rgb(235, 245, 255);\n"
"    border: 1px solid grey;\n"
"}")
        self.tbl_filasResultados.setFrameShape(QtWidgets.QFrame.HLine)
        self.tbl_filasResultados.setAlternatingRowColors(True)
        self.tbl_filasResultados.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tbl_filasResultados.setGridStyle(QtCore.Qt.SolidLine)
        self.tbl_filasResultados.setWordWrap(True)
        self.tbl_filasResultados.setObjectName("tbl_filasResultados")
        self.tbl_filasResultados.setColumnCount(0)
        self.tbl_filasResultados.setRowCount(0)
        self.tbl_filasResultados.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_filasResultados.horizontalHeader().setDefaultSectionSize(180)
        self.tbl_filasResultados.horizontalHeader().setMinimumSectionSize(180)
        self.tbl_filasResultados.horizontalHeader().setStretchLastSection(False)
        self.tbl_filasResultados.verticalHeader().setVisible(False)
        self.tbl_filasResultados.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_filasResultados.verticalHeader().setDefaultSectionSize(30)
        self.tbl_filasResultados.verticalHeader().setMinimumSectionSize(23)
        self.verticalLayout.addWidget(self.tbl_filasResultados)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_eliminarFila = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_eliminarFila.sizePolicy().hasHeightForWidth())
        self.btn_eliminarFila.setSizePolicy(sizePolicy)
        self.btn_eliminarFila.setMinimumSize(QtCore.QSize(141, 41))
        self.btn_eliminarFila.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_eliminarFila.setFont(font)
        self.btn_eliminarFila.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_eliminarFila.setObjectName("btn_eliminarFila")
        self.horizontalLayout_3.addWidget(self.btn_eliminarFila)
        self.btn_insertarFila = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_insertarFila.sizePolicy().hasHeightForWidth())
        self.btn_insertarFila.setSizePolicy(sizePolicy)
        self.btn_insertarFila.setMinimumSize(QtCore.QSize(141, 41))
        self.btn_insertarFila.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_insertarFila.setFont(font)
        self.btn_insertarFila.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_insertarFila.setObjectName("btn_insertarFila")
        self.horizontalLayout_3.addWidget(self.btn_insertarFila)
        self.btn_insertarCol = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_insertarCol.sizePolicy().hasHeightForWidth())
        self.btn_insertarCol.setSizePolicy(sizePolicy)
        self.btn_insertarCol.setMinimumSize(QtCore.QSize(141, 41))
        self.btn_insertarCol.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_insertarCol.setFont(font)
        self.btn_insertarCol.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_insertarCol.setObjectName("btn_insertarCol")
        self.horizontalLayout_3.addWidget(self.btn_insertarCol)
        self.btn_eliminarCol = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_eliminarCol.sizePolicy().hasHeightForWidth())
        self.btn_eliminarCol.setSizePolicy(sizePolicy)
        self.btn_eliminarCol.setMinimumSize(QtCore.QSize(141, 41))
        self.btn_eliminarCol.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_eliminarCol.setFont(font)
        self.btn_eliminarCol.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_eliminarCol.setObjectName("btn_eliminarCol")
        self.horizontalLayout_3.addWidget(self.btn_eliminarCol)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_confirmar = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_confirmar.sizePolicy().hasHeightForWidth())
        self.btn_confirmar.setSizePolicy(sizePolicy)
        self.btn_confirmar.setMinimumSize(QtCore.QSize(141, 41))
        self.btn_confirmar.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_confirmar.setFont(font)
        self.btn_confirmar.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_confirmar.setObjectName("btn_confirmar")
        self.horizontalLayout.addWidget(self.btn_confirmar)
        self.btn_crearDesdeExcel = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_crearDesdeExcel.sizePolicy().hasHeightForWidth())
        self.btn_crearDesdeExcel.setSizePolicy(sizePolicy)
        self.btn_crearDesdeExcel.setMinimumSize(QtCore.QSize(141, 41))
        self.btn_crearDesdeExcel.setMaximumSize(QtCore.QSize(141, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btn_crearDesdeExcel.setFont(font)
        self.btn_crearDesdeExcel.setStyleSheet("QPushButton {\n"
"    border: 1px solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(173, 173, 173);\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(218, 255, 215);\n"
"}")
        self.btn_crearDesdeExcel.setObjectName("btn_crearDesdeExcel")
        self.horizontalLayout.addWidget(self.btn_crearDesdeExcel)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.widget_3)
        WindowTablaResult.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WindowTablaResult)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        WindowTablaResult.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WindowTablaResult)
        self.statusbar.setObjectName("statusbar")
        WindowTablaResult.setStatusBar(self.statusbar)

        self.retranslateUi(WindowTablaResult)
        QtCore.QMetaObject.connectSlotsByName(WindowTablaResult)

    def retranslateUi(self, WindowTablaResult):
        _translate = QtCore.QCoreApplication.translate
        WindowTablaResult.setWindowTitle(_translate("WindowTablaResult", "Tabla Filas-Resultados"))
        self.btn_eliminarFila.setText(_translate("WindowTablaResult", "Eliminar fila"))
        self.btn_insertarFila.setText(_translate("WindowTablaResult", "Insertar fila"))
        self.btn_insertarCol.setText(_translate("WindowTablaResult", "Insertar columna"))
        self.btn_eliminarCol.setText(_translate("WindowTablaResult", "Eliminar columna"))
        self.btn_confirmar.setText(_translate("WindowTablaResult", "Confirmar cambios"))
        self.btn_crearDesdeExcel.setText(_translate("WindowTablaResult", "Crear tabla (cuidado!)"))
